### ISSUE TITLE
Feature: device bypass

### ISSUE THREAD

**Issue by camokatuk** [AxelStrem/Bro-binary#26]
Pls implement bypass button on devices bro

**Comment by AxelStrem** [comment]
how the fuck is it supposed to work bro? devices are not "effects" (most of them anyway), they don't have fixed "IN" and "OUT" connectors, and the data flow is semantically altered by the device more often than not.

The ones that do have some "bypassing potential" are **Filter** and **Transform**, but you can tweak them into an identity transform quick enough, no?

**Comment by AxelStrem** [comment]
After some consideration, it has been decided that [this feature](https://github.com/AxelStrem/Bro-binary/issues/27) should be implemented first.

Closing this one until then
